### ISSUE TITLE
Sorting on 'Task' category in Task List on a campaign's page doesn't sort correctly

### ISSUE THREAD

**Issue by krismadden** [bootphon/seshat-angular-client#7]
(it does something the first time its clicked. but it's not sorting by task type)

http://localhost:4200/admin/campaign/[campaign]

**Comment by krismadden** [comment]
also here http://localhost:4200/annotator/tasks

**Comment by hadware** [comment]
solved in 555f09ab28cf8a1b189d71cd3c916c1b16b44404
